 /******************************************************************************
 *
 * Module: ultrasonic
 *
 * File Name: ultrasonic.c
 *
 * Description: Source file for the ultrasonic sensor driver
 *
 * Author: Abdelrahman Ehab
 *
 *******************************************************************************/

/*******************************************************************************
 *                      		Include Header	                               *
 *******************************************************************************/
#include <avr/io.h>
#include <util/delay.h>
#include "ultrasonic.h"
#include "icu.h"
#include "gpio.h"

/*******************************************************************************
 *                         	  Global variables                                 *
 *******************************************************************************/
uint8  g_edgeCount = 0; /* to count number of edge */
static uint16 g_timeLow = 0; /* To get the time to reach required falling edge from echo pin */
static uint16 g_distance = 0; /* variable to save the sensed distance value in it */
/*******************************************************************************
 *                         	Function Declaration                                *
 *******************************************************************************/
/*
 * Description:
 * This is the call back function called by the ICU driver.
 * This is used to calculate the high time (pulse time) generated by the ultrasonic sensor.
 */
 void Ultrasonic_edgeProcessing(void)
 {
	 g_edgeCount++; /* To call back this function two times to get the value of ECHO puls */
	 if(g_edgeCount == 1)
	 {
		 ICU_clearTimerValue(); /* Clear timer to start count from zero second */

		 ICU_setEdgeDetectionType(FALLING); /* change edge detection edge to get time required to reach the falling edge */
	 }
	 else if(g_edgeCount == 2)
	 {
		 g_timeLow = ICU_getInputCaptureValue(); /* Get the time required to reach falling edge in a variable */

		 ICU_clearTimerValue(); /* clear timer again */
		 ICU_setEdgeDetectionType(RISING); /* return edge detection to rising edge for next process */
		 g_edgeCount = 0; /* clear counter to start from beginning */
	 }
 }

/*
 * Description:
 * Initialize the ICU driver as required.
 * Setup the ICU call back function.
 * Setup the direction for the trigger pin as output pin through the GPIO driver.
 */
void Ultrasonic_init(void)
{
	/*
	 * ICU frequency = F_CPU/8, and detect the raising edge as the first edge.
	 * the ICU will call back Ultrasonic_edgeProcessing function when it detect an edge.
	 */
	ICU_ConfigType config = {F_CPU_8,RISING};
	ICU_init(&config);

	ICU_setCallBack(Ultrasonic_edgeProcessing);
	/*	Make trigger pin as output pin	*/
	GPIO_setupPinDirection(TRIGGER_PORT_ID, TRIGGER_PIN_ID, PIN_OUTPUT);
}

/*
 * Description:
 * Send the Trigger pulse to the ultrasonic.
 *
 */
void Ultrasonic_Trigger(void)
{
	GPIO_writePin(TRIGGER_PORT_ID, TRIGGER_PIN_ID, LOGIC_HIGH); /* Trigger pin on */
	_delay_us(20); /*When a pulse of (at least) 10µsecs given to the Triggerg pin, 8 pulses of 40 kHz are generated.*/
	GPIO_writePin(TRIGGER_PORT_ID, TRIGGER_PIN_ID, LOGIC_LOW); /* Trigger pin off */
}

/*
 * Description:
 * Send the trigger pulse by using Ultrasonic_Trigger function.
 * Start the measurements by the ICU from this moment.
 */
uint16 Ultrasonic_readDistance(void)
{
	Ultrasonic_Trigger(); /* Trigger ultrasonic once to measure only one value */

	g_distance = (g_timeLow * 0.0173); /* Distance equation */
	return g_distance; /* return distance value */
}
